-- CreateTable
CREATE TABLE "VillageConfig" (
    "id" SERIAL NOT NULL,
    "villageCode" VARCHAR(10) NOT NULL,
    "villageName" TEXT NOT NULL,
    "districtCode" VARCHAR(6),
    "districtName" TEXT,
    "regencyCode" VARCHAR(4),
    "regencyName" TEXT,
    "provinceCode" VARCHAR(2),
    "provinceName" TEXT,
    "officeAddress" TEXT,
    "postalCode" VARCHAR(10),
    "phone" TEXT,
    "email" TEXT,
    "website" TEXT,
    "establishedYear" INTEGER,
    "description" TEXT,
    "areaSize" DOUBLE PRECISION,
    "areaUnit" TEXT DEFAULT 'km²',
    "populationTotal" INTEGER DEFAULT 0,
    "hamletCount" INTEGER DEFAULT 0,
    "rwCount" INTEGER DEFAULT 0,
    "rtCount" INTEGER DEFAULT 0,
    "borderNorth" TEXT,
    "borderEast" TEXT,
    "borderSouth" TEXT,
    "borderWest" TEXT,
    "elevation" INTEGER,
    "latitude" DECIMAL(10,8),
    "longitude" DECIMAL(11,8),
    "logoUrl" TEXT,
    "officePhotoUrl" TEXT,
    "vision" TEXT,
    "mission" TEXT,
    "slogan" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VillageConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "VillageConfig_villageCode_key" ON "VillageConfig"("villageCode");
